spring:
  application:
    name: jwt
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt?createDatabaseIfNotExist=true
    username: root
    password: '2005@Hau'
server:
  port: 8081